basePath: /
definitions:
  github_com_tadilbek11kz_ePharma-backend_pkg_inventory.CreateInventoryRequest:
    properties:
      pharmacy_id:
        type: string
      price:
        type: number
      product_id:
        type: string
      quantity:
        type: integer
    required:
    - pharmacy_id
    - price
    - product_id
    - quantity
    type: object
  github_com_tadilbek11kz_ePharma-backend_pkg_inventory.Inventory:
    properties:
      createdAt:
        type: string
      id:
        type: string
      pharmacy_id:
        type: string
      price:
        type: number
      product_id:
        type: string
      quantity:
        type: integer
      updatedAt:
        type: string
    required:
    - pharmacy_id
    - price
    - product_id
    - quantity
    type: object
  github_com_tadilbek11kz_ePharma-backend_pkg_inventory.UpdateInventoryRequest:
    properties:
      price:
        type: number
      quantity:
        type: integer
    type: object
  github_com_tadilbek11kz_ePharma-backend_pkg_notification.CreateNotificationRequest:
    properties:
      email:
        type: string
      product_id:
        type: string
    required:
    - email
    - product_id
    type: object
  github_com_tadilbek11kz_ePharma-backend_pkg_notification.Notification:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      product_id:
        type: string
      updatedAt:
        type: string
    required:
    - email
    - product_id
    type: object
  github_com_tadilbek11kz_ePharma-backend_pkg_pharmacy.CreatePharmacyRequest:
    properties:
      description:
        type: string
      location:
        type: string
      name:
        type: string
    required:
    - description
    - location
    - name
    type: object
  github_com_tadilbek11kz_ePharma-backend_pkg_pharmacy.Pharmacy:
    properties:
      createdAt:
        type: string
      descritpion:
        type: string
      id:
        type: string
      location:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    required:
    - location
    - name
    type: object
  github_com_tadilbek11kz_ePharma-backend_pkg_pharmacy.UpdatePharmacyRequest:
    properties:
      description:
        type: string
      location:
        type: string
      name:
        type: string
    type: object
  github_com_tadilbek11kz_ePharma-backend_pkg_product.CreateProductRequest:
    properties:
      brand_name:
        type: string
      dispence_mode:
        type: string
      dosage:
        type: string
      generic_name:
        type: string
      image:
        type: string
      insurance_plan:
        type: string
      manufacturer_name:
        type: string
      package_size:
        type: string
      strength:
        type: string
    required:
    - brand_name
    - dispence_mode
    - dosage
    - generic_name
    - image
    - insurance_plan
    - manufacturer_name
    - package_size
    - strength
    type: object
  github_com_tadilbek11kz_ePharma-backend_pkg_product.Product:
    properties:
      brand_name:
        type: string
      createdAt:
        type: string
      dispence_mode:
        type: string
      dosage:
        type: string
      generic_name:
        type: string
      id:
        type: string
      image:
        type: string
      insurance_plan:
        type: string
      manufacturer_name:
        type: string
      package_size:
        type: string
      strength:
        type: string
      updatedAt:
        type: string
    required:
    - brand_name
    - dispence_mode
    - dosage
    - generic_name
    - image
    - insurance_plan
    - manufacturer_name
    - package_size
    - strength
    type: object
  github_com_tadilbek11kz_ePharma-backend_pkg_product.UpdateProductRequest:
    properties:
      brand_name:
        type: string
      dispence_mode:
        type: string
      dosage:
        type: string
      generic_name:
        type: string
      image:
        type: string
      insurance_plan:
        type: string
      manufacturer_name:
        type: string
      package_size:
        type: string
      strength:
        type: string
    type: object
  github_com_tadilbek11kz_ePharma-backend_pkg_user.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  github_com_tadilbek11kz_ePharma-backend_pkg_user.LoginUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  github_com_tadilbek11kz_ePharma-backend_pkg_user.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
      updatedAt:
        type: string
    required:
    - email
    - name
    type: object
host: 10.225.78.198:8080
info:
  contact: {}
  description: This is a service for ePharma project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: ePharma API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: login user
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_user.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Login an user
      tags:
      - auth
  /auth/logout:
    get:
      consumes:
      - application/json
      description: logout user
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Logout user
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: refresh token
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Refresh an access token
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: register user
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_user.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_user.User'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Register an user
      tags:
      - auth
  /inventory:
    get:
      consumes:
      - application/json
      description: Get all inventories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_inventory.Inventory'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get all inventories
      tags:
      - inventory
    post:
      consumes:
      - application/json
      description: Create inventory
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_inventory.CreateInventoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_inventory.Inventory'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Create inventory
      tags:
      - inventory
  /inventory/{id}:
    delete:
      consumes:
      - application/json
      description: Delete inventory
      parameters:
      - description: Inventory ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete inventory
      tags:
      - inventory
    get:
      consumes:
      - application/json
      description: Get inventory
      parameters:
      - description: Inventory ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_inventory.Inventory'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get inventory
      tags:
      - inventory
    put:
      consumes:
      - application/json
      description: Update inventory
      parameters:
      - description: Inventory ID
        in: path
        name: id
        required: true
        type: string
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_inventory.UpdateInventoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_inventory.Inventory'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update inventory
      tags:
      - inventory
  /notification:
    post:
      consumes:
      - application/json
      description: Create notification
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_notification.CreateNotificationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_notification.Notification'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Create notification
      tags:
      - notification
  /notification/{id}:
    delete:
      consumes:
      - application/json
      description: Delete notification
      parameters:
      - description: Notification ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete notification
      tags:
      - notification
  /pharmacy:
    get:
      consumes:
      - application/json
      description: get all pharmacies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_pharmacy.Pharmacy'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get all pharmacies
      tags:
      - pharmacy
    post:
      consumes:
      - application/json
      description: create pharmacy
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_pharmacy.CreatePharmacyRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_pharmacy.Pharmacy'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Create a pharmacy
      tags:
      - pharmacy
  /pharmacy/{id}:
    delete:
      consumes:
      - application/json
      description: delete pharmacy
      parameters:
      - description: Pharmacy ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete a pharmacy
      tags:
      - pharmacy
    get:
      consumes:
      - application/json
      description: get pharmacy
      parameters:
      - description: Pharmacy ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_pharmacy.Pharmacy'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get a pharmacy
      tags:
      - pharmacy
    put:
      consumes:
      - application/json
      description: update pharmacy
      parameters:
      - description: Pharmacy ID
        in: path
        name: id
        required: true
        type: string
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_pharmacy.UpdatePharmacyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_pharmacy.Pharmacy'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update a pharmacy
      tags:
      - pharmacy
  /product:
    get:
      consumes:
      - application/json
      description: get products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_product.Product'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get all products
      tags:
      - product
    post:
      consumes:
      - application/json
      description: create product
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_product.CreateProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_product.Product'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Create a product
      tags:
      - product
  /product/{id}:
    delete:
      consumes:
      - application/json
      description: delete product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete a product
      tags:
      - product
    get:
      consumes:
      - application/json
      description: get product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_product.Product'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get a product
      tags:
      - product
    put:
      consumes:
      - application/json
      description: update product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_product.UpdateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_product.Product'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update a product
      tags:
      - product
  /product/{id}/inventory:
    get:
      consumes:
      - application/json
      description: get product inventory
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_tadilbek11kz_ePharma-backend_pkg_pharmacy.Pharmacy'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get product inventory
      tags:
      - product
swagger: "2.0"
